language:  generic

notifications:
    slack:
      rooms:
        - nozeio:LIFY1Jtkx0FRcLq3u1WliHRZ
        - apacheexpress:9z2IfvxZfENp0TFmiYCgyUKz
matrix:
    include:
        - os:   Linux
          dist: trusty
          env:  MOD_SWIFT="https://github.com/modswift/mod_swift/archive/0.8.0.tar.gz" SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-3.0.2-release/ubuntu1404/swift-3.0.2-RELEASE/swift-3.0.2-RELEASE-ubuntu14.04.tar.gz"
          sudo: required
        - os:   Linux
          dist: trusty
          env:  MOD_SWIFT="https://github.com/modswift/mod_swift/archive/0.8.0.tar.gz" SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-3.1.1-release/ubuntu1404/swift-3.1.1-RELEASE/swift-3.1.1-RELEASE-ubuntu14.04.tar.gz"
          sudo: required
        - os:   osx
          osx_image: xcode8.2

before_install:
    - ./.travis.d/before-install.sh

install:
    - ./.travis.d/install.sh

script:
    - export PATH="$HOME/usr/bin:$PATH"
    - swift build
